fix: fire transition events for reduced motion
AlaskaAirlines/WebCoreStyleSheets pull request #111
Opened 2021-12-03 22:58 UTC by geoffrich

# Alaska Airlines Pull Request

Prerequisite to fix https://github.com/AlaskaAirlines/auro-accordion/issues/42.

## Summary:

The reduced motion settings disabled transitions, which caused events like `transitionend` not to play. This affected auro-accordion logic (see related issue for more details).

Instead, I set transition-duration to a small value so that transitions still play, but appear instantaneous. 

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-12-03 23:33 UTC, geoffrich commented
Once merged, I'll open an auro-accordion PR that updates this dep. This should resolve the issue.

2021-12-04 00:39 UTC, blackfalcon requested changes
Do you know why there is a 20k diff with package-lock?

2021-12-04 00:39 UTC, blackfalcon commented on src/_core.scss
> +      animation-duration: 0.01ms !important;
This needs to be better documented in the code that this IS why this was coded this way. This PR is only describing the WHAT and it's not clear as to the WHY. 

The comments in this code feed the automated docs. Please be sure to run `build:sassdoc` in order to update the automated docs.

2021-12-04 03:11 UTC, geoffrich commented
Ah, sorry @blackfalcon I committed that accidentally. Will revert and force push a fresh commit.

2021-12-06 05:07 UTC, blackfalcon submitted a review, later dismissed

2021-12-06 05:10 UTC, blackfalcon approved these changes

2021-12-06 05:10 UTC, merged

2021-12-06 05:12 UTC, AuroDesignSystem commented
:tada: This PR is included in version 3.7.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/webcorestylesheets/v/3.7.3)
- [GitHub release](https://github.com/AlaskaAirlines/WebCoreStyleSheets/releases/tag/v3.7.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: