feat: new list styles
AlaskaAirlines/WebCoreStyleSheets pull request #132
Opened 2022-11-18 23:45 UTC by jrbromberg

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #115

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-11-18 23:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/WebCoreStyleSheets?pullRequest=132) it.</sub>

2022-11-21 23:29 UTC, blackfalcon requested changes

2022-11-21 23:29 UTC, blackfalcon commented on src/utilityClasses/_listProperties.scss
> +}
Please add a new line at the end of the file.

2022-11-21 23:29 UTC, blackfalcon commented on src/utilityClasses/_listProperties.scss
> +}
@leeejune do we have a design spec that this is developed against?

2022-11-28 21:36 UTC, leeejune commented on src/utilityClasses/_listProperties.scss
> +}
@blackfalcon I am not aware of any specs!

2022-12-09 22:45 UTC, braven112 commented
Closing in favor of this PR with the update design https://github.com/AlaskaAirlines/WebCoreStyleSheets/pull/138

2022-12-09 22:45 UTC, closed without merging