Junelee/alter design/#115
AlaskaAirlines/WebCoreStyleSheets pull request #138
Opened 2022-12-09 01:42 UTC by leeejune

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #115  (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._
Changed spacing for all types of lists and bullet size.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-12-09 01:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=138) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: leeejune<br/>:x: jrbromberg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/WebCoreStyleSheets?pullRequest=138) it.</sub>

2022-12-09 01:43 UTC, leeejune commented
@braven112 I made some changes here!

2022-12-09 17:48 UTC, braven112 commented on src/utilityClasses/_listProperties.scss
> +  padding-left: 2*$auro-size-200; //calc(x*x)
We can remove this comment and use the calc function to generate this value..

2022-12-09 17:48 UTC, braven112 commented on src/utilityClasses/_listProperties.scss
>      text-indent: -$auro-size-200;
This should be a css variable instead

2022-12-15 18:13 UTC, blackfalcon commented
I removed the merge from @braven112 but accidentally removed the last two commits from @leeejune. I reached out to @leeejune to force-push her last version of the branch so that we can have that work. Then I can rebase off of main and merge this work.

2022-12-15 18:14 UTC, blackfalcon requested changes
Requires missing commits from @leeejune

2022-12-20 16:34 UTC, blackfalcon approved these changes

2022-12-20 16:34 UTC, merged

2022-12-20 16:36 UTC, blackfalcon commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/webcorestylesheets/v/4.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/WebCoreStyleSheets/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: