Update references to new auro breakpoints
AlaskaAirlines/WebCoreStyleSheets pull request #153
Opened 2023-05-10 17:37 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #146 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Update current and add new auro breakpoints based on new grid breakpoint update.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-05-10 19:49 UTC, blackfalcon requested changes

2023-05-10 19:49 UTC, blackfalcon commented on src/_breakpoints.scss
> +///   $auro-breakpoint-xl: 1232px;
These changes constitute a BREAKING CHANGE

2023-05-11 17:25 UTC, blackfalcon requested changes
Releasing a breaking change like this will result in teams having to review existing UIs that are built using the current model. That will never happen so teams will be resistant to updating to this new model and having to possibly adjust page layouts. 

We need to add this as a new feature while supporting the legacy values that can be deprecated.

2023-05-23 17:17 UTC, jason-capsule42 approved these changes

2023-05-23 17:33 UTC, jason-capsule42 approved these changes

2023-05-23 17:34 UTC, merged