feat(gridstyle): add a new class for one column grid layout
AlaskaAirlines/WebCoreStyleSheets pull request #154
Opened 2023-05-12 23:08 UTC by marnel-mangrubang

# Alaska Airlines Pull Request

## Summary:
Needed to add a new class in WCSS to support one column grid layout. This is a pre-requisite work for the AuroDocSite, in order to provide a demo page that utilizes a grid layout.

- Added a new `_grids.scss` file that consists of grid styling to be used for a one column layout.
- Added mixins to allow for updating the value of the `max-width`, `margin` and `gap`.

## Type of change:
- [X] New capability

## Checklist:
- [ ] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update.(By importing distribution file of the new grids.scss and adding it to the AuroDocSite repo manually.)

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-05-15 17:13 UTC, blackfalcon requested changes
The commit message is incorrectly formatted. Please correct.

2023-05-15 17:13 UTC, blackfalcon commented on src/_grids.scss
> +  }
These values should be using either Sass variables or CSS variables.

2023-05-15 17:13 UTC, blackfalcon commented on src/_grids.scss
> +
Extra lines?

2023-05-15 17:13 UTC, blackfalcon commented on src/_grids.scss
> +#{$scope}.#{$prefix}the_griddy {
`the_griddy`?

2023-05-15 18:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=154) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=154) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: marnel-mangrubang<br/>:x: chethanayasa<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/WebCoreStyleSheets?pullRequest=154) it.</sub>

2023-05-15 20:57 UTC, blackfalcon requested changes

2023-05-15 20:57 UTC, blackfalcon commented on src/_grids.scss
> +}
Files should always have a single line after.

2023-05-15 20:57 UTC, blackfalcon commented on src/_grids.scss
> +  @include grid_width($auro-grid-width);
https://github.com/AlaskaAirlines/WebCoreStyleSheets/actions/runs/4985003032/jobs/8924097100#step:6:23

These are not tokens, where are these defined?

2023-05-15 23:33 UTC, marnel-mangrubang commented on src/_grids.scss
> +  }
Defined the sass variables used in the new grid class style.

2023-05-15 23:35 UTC, marnel-mangrubang commented on src/_grids.scss
> +#{$scope}.#{$prefix}the_griddy {
Courtesy of Minnesota Vikings Wide receiver(Justin Jefferson) dance known as 'The Griddy', even though Allan Davis(high school player) created it originally.

2023-05-15 23:36 UTC, marnel-mangrubang commented on src/_grids.scss
> +#{$scope}.#{$prefix}the_griddy {
Renamed `the_griddy` to `grid`.

2023-05-15 23:37 UTC, marnel-mangrubang commented on src/_grids.scss
> +  @include grid_width($auro-grid-width);
Refactored this and defined the value at the top of the page.

2023-05-16 16:28 UTC, blackfalcon requested changes
We are pretty close. I also created a new issue to add the grid spacing token. 

- https://github.com/AlaskaAirlines/AuroDesignTokens/issues/112

Once we are done with this work, we can 1:1 to clean up the history before we merge this PR.

2023-05-16 16:28 UTC, blackfalcon commented on src/_grids.scss
> +$auro-grid-spacing: 8px;
These really should be variables outside the scope of this document. If these need to change, I am not sure that this will be the first place someone looks? 

`$auro-grid-width` === `$auro-grid-breakpoint-xl`
`$auro-grid-spacing` == `$auro-size-100` (not hard px, uses REM)

We can add a new token for grid spacing and recommend using that as a variable.

2023-05-16 16:35 UTC, blackfalcon commented on src/_grids.scss
> +$auro-grid-spacing: 8px;
Thinking about this a little more, maybe it makes better sense to have a specific `grid-width` token as not to directly relate the breakpoint with the max grid size.

2023-05-16 22:54 UTC, marnel-mangrubang commented on src/_grids.scss
> +$auro-grid-spacing: 8px;
We ended up using the existing tokens:
- `$auro-grid-breakpoint-xl` for the max-width
- `$auro-grid-gutter-xs` for the gap
- `$auro-grid-margin-xs` for the margin

2023-05-18 02:55 UTC, jason-capsule42 commented
Is there a working demo somewhere that shows all these new styles in action? I feel without that all I could review is if the CSS is syntax/semantically correct without knowledge about if it seems to do the right thing.

2023-05-18 21:22 UTC, merged