feat: rename 2 column layout class names and styling
AlaskaAirlines/WebCoreStyleSheets pull request #159
Opened 2023-06-17 00:00 UTC by marnel-mangrubang

BREAKING CHANGE: This update will remove the existing 2 column layout classes and replace them with updated class names and stylings.

# Alaska Airlines Pull Request
This pull request will remove the existing selectors for the 2 column grid layouts.
The following is a summary of the changes made:

1. Removed selectors to be aware of that **have been removed.**

- .grid

2. Removed mixins

- 

**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-06-20 19:12 UTC, blackfalcon requested changes

2023-06-20 19:12 UTC, blackfalcon commented on src/_breakpoints.scss
> +  @media screen and (min-width: $auro-grid-breakpoint-xl) {
One thing I want to do now that CSS variables are used in all browsers is to STOP using Sass variables. 

```suggestion
  @media screen and (min-width: var(--auro-grid-breakpoint-xl) {
```

By doing this, we can remove the hard-coded expectation and not inadvertently break a test just because the value of a variable changed.

2023-06-20 19:12 UTC, blackfalcon commented on tests/breakpoint.spec.scss
> +        @media screen and (min-width: 1232px) {
```suggestion
        @media screen and (min-width: var(--auro-grid-breakpoint-xl)) {
```

See previous comment about replacing Sass variables with CSS custom properties.

2023-06-20 23:43 UTC, marnel-mangrubang commented on src/_breakpoints.scss
> +  @media screen and (min-width: $auro-grid-breakpoint-xl) {
Replaced the use of Sass variables with CSS variables in the media query mixins as well as their unit tests.

2023-07-31 22:42 UTC, blackfalcon approved these changes

2023-07-31 22:43 UTC, merged

2023-07-31 22:45 UTC, blackfalcon commented
:tada: This PR is included in version 4.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/webcorestylesheets/v/4.7.0)
- [GitHub release](https://github.com/AlaskaAirlines/WebCoreStyleSheets/releases/tag/v4.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: