Update to reference Lit #161
AlaskaAirlines/WebCoreStyleSheets pull request #162
Opened 2023-06-29 03:23 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Changes to be committed:
modified:   docs/index.html
modified:   src/auroElement/README.md
modified:   src/auroElement/auroElement.js

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-07-05 03:53 UTC, jason-capsule42 requested changes
The changes look good but the PR automated comments say there is a conflict with `docs/index.html` that must be resolved.

2023-07-07 19:57 UTC, blackfalcon commented
@jason-capsule42 conflict as been resolved.

2023-07-11 19:25 UTC, jason-capsule42 approved these changes

2023-07-11 19:33 UTC, merged

2023-07-11 19:35 UTC, blackfalcon commented
:tada: This PR is included in version 4.6.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/webcorestylesheets/v/4.6.1)
- [GitHub release](https://github.com/AlaskaAirlines/WebCoreStyleSheets/releases/tag/v4.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: