docs: add file for idiomatic css
AlaskaAirlines/WebCoreStyleSheets pull request #72
Opened 2021-05-03 05:45 UTC by jason-capsule42

# Alaska Airlines Pull Request

**Fixes:** #70

## Summary:

This change adds a new document file describing idiomatic css. This file will require a change to AuroDocSite to make it live.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-05-04 18:45 UTC, blackfalcon requested changes
There is a new branch pushed to the doc site for a review of this document in context. 
https://github.com/AlaskaAirlines/AuroDocsSite/compare/wcss-addDocForIdiomaticCss%2370?expand=1

npm link WCSS locally. 

In the issue there is... Move [CSS Conventions doc](https://github.com/AlaskaAirlines/auro/blob/master/src/CSSCONVENTIONS.md) from the generic Auro repo to the WCSS repo. 

It's suggested in the issue to relocate the doc and add a brief description of idiomatic CSS inline with the other CSS conventions and in there will be a link to this new doc.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +1. [What is Idiomatic CSS?](#idiomatic-css)
```suggestion
1. <auro-hyperlink relative href="#idiomatic-css">What is Idiomatic CSS?</auro-hyperlink>
```

Due to the way that the markdown processor is working to dynamically determine the difference between an internal versus external URL, the markdown link is being seen as an external link. 

The easiest way around this is to use the `auro-hyperlink` CE.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +What is `idiomatic`?
```suggestion
What is __idiomatic__?
```

This is not a code reference, so I'd suggest not using code highlighting. If you are looking for emphasis, I'd suggest using italics or maybe bold.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +When we speak or write thoughts and ideas we strive to construct our words in a manner that is easily understood, clear, concise, logical and does not require excessive effort on the part of the list
```suggestion
When we speak or write thoughts and ideas we strive to construct our words in a manner that is easily understood, clear, concise, logical, and does not require excessive effort on the part of the listener to understand the context or message. __Idiomatic CSS__ means to write our style code with similar goals. We aim for more than just _technically correct_ code.
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +<a name="idiomatic-css"></a>
Something to consider when using anchor tags is that the sub-nav header is fixed and takes up space. So when you click the link for the page scroll, some of the content will be hidden and the user will have to scroll down. 

Maybe placing the anchor higher up in the content can compensate.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +```scss
The syntax highlighter in the doc site currently doesn't support `scss` so all the code returns in a single color. 

Using `css` will work.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +  // valid
A phrase I try to use as much as possible with setting standards is `compliant` and `non-compliant`. 

It is heavily used in the CSS conventions document.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +```scss
There needs to be a line break between lines 78 and 79. 

The markdown processor is globbing this text together and the code rendering is not working as expected.

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> + * Don't hesitate to use longer dscriptions that would take multiple lines or
```suggestion
 * Don't hesitate to use longer descriptions that would take multiple lines or
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> + * multiple sentances. While comments should be simple, they should also not
```suggestion
 * multiple sentences. While comments should be simple, they should also not
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +* Indentation sbould be 2 spaces.
```suggestion
* Indentation should be 2 spaces.
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +* Selector combinations should not have more than a single class, attribute and type.
While this is not incorrect, the CSS conventions we have speak against using these types of selectors. Illustrating this as a `valid` option sends mixed messages. 

> A term I like to use is a Pure Selector. Pure Selectors should NEVER have a dependency on a parent selector, nor should it have any side-effects when used as a descendant selector. 

What do you think?

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +* SCSS $ variables should be at the top of the selector block properties
```suggestion
* Sass `$` variables should be at the top of the selector block properties
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +  block.
Why is this on a new line?

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +  block, after any `@extend` statements.
Do you use a code formatter that inserts line breaks?

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +* Color hex valuies use lowercase and shorthand. e.g., `#fff`.
```suggestion
* Color hex values use lowercase and shorthand. e.g., `#fff`.
```

2021-05-04 18:45 UTC, blackfalcon commented on IDIOMATICCSS.md
> +Declaractions should be consistently grouped and ordered.
```suggestion
Declarations should be consistently grouped and ordered.
```

2021-05-05 01:26 UTC, jason-capsule42 commented on IDIOMATICCSS.md
> +* Selector combinations should not have more than a single class, attribute and type.
@blackfalcon good catch - would you agree that this is better?

```
#selector1 {
  &.selector2 {
    //valid
  }
}

#selector1.selector2 {
  //invalid
}
```

2021-05-05 01:42 UTC, jason-capsule42 commented on IDIOMATICCSS.md
> +<a name="idiomatic-css"></a>
@blackfalcon do you mean just adding one or more empty lines in between the anchor and the actual section title content?

2021-05-05 04:02 UTC, blackfalcon commented on IDIOMATICCSS.md
> +<a name="idiomatic-css"></a>
No, empty lines won't matter. If you don't mind, I can do it. I have the docs site branch ready to go.

2021-05-05 04:07 UTC, blackfalcon commented
Probably want to squash these individual doc commits. FYI there is a feature to group all these kinds of commits into a single commit that can be re-worded.

2021-05-05 15:13 UTC, jason-capsule42 commented on IDIOMATICCSS.md
> +<a name="idiomatic-css"></a>
Go for it, @blackfalcon.

2021-05-05 15:23 UTC, geoffrich commented on IDIOMATICCSS.md
> +  // compliant
Should these "compilant" comments use `/* compliant */` so it's valid CSS?

2021-05-05 15:23 UTC, geoffrich commented on IDIOMATICCSS.md
> +* Only one declaration per line, a single space after the colon and always use an ending semi-colon
```suggestion
* Only one declaration per line, a single space after the colon and always use an ending semicolon
```

2021-05-05 21:52 UTC, blackfalcon approved these changes

2021-05-05 21:52 UTC, merged

2021-05-05 22:05 UTC, blackfalcon commented
Page is located at http://auro.alaskaair.com/webcorestylesheets/idiomatic-css