style: update styles for idiomatic compliance
AlaskaAirlines/WebCoreStyleSheets pull request #73
Opened 2021-05-06 17:11 UTC by jason-capsule42

# Alaska Airlines Pull Request

**Fixes:** #71

## Summary:

Update WebCoreStylesheets SCSS files to follow compliance with new style guide for idiomatic CSS http://auro.alaskaair.com/webcorestylesheets/idiomatic-css

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-05-10 18:38 UTC, geoffrich commented on src/_essentials.scss
> +#{$sym}#{$prefix}p {
What happened to `{$scope}`?

2021-05-10 18:38 UTC, geoffrich commented on src/_normalize.scss
> +  overflow: visible; /* 2 */
Looks like the `/* 2 */` comments are referenced in the above docs. It's a little weird to have these out of order -- should we swap 1 & 2 so it's still sequential?

2021-05-10 18:38 UTC, geoffrich commented on src/_normalize.scss
> +  color: inherit; /* 2 */
See above re: sequential ordering

2021-05-10 18:38 UTC, geoffrich commented on src/_normalize.scss
> +  -webkit-appearance: textfield; /* 1 */
Sequential ordering

2021-05-10 18:38 UTC, geoffrich commented on src/_normalize.scss
> +#{$scope}::-webkit-search-decoration {
Was the attribute selector intentionally removed?

2021-05-10 18:38 UTC, geoffrich commented on src/_normalize.scss
> +  -webkit-appearance: button; /* 1 */
Sequential ordering

2021-05-10 18:38 UTC, geoffrich commented on src/componentSupport/_table.scss
> +  border-collapse: collapse;
Should border properties be grouped together?

2021-05-10 18:38 UTC, geoffrich commented on src/utilityClasses/_responsive.scss
> +    display: none $important;
Have we tested these selector changes? Since media queries don't add specificity, this might have display:none win out in all cases.

2021-05-10 19:33 UTC, blackfalcon requested changes

2021-05-10 19:33 UTC, blackfalcon commented on src/_essentials.scss
> +  font-weight: $auro-text-body-default-weight; // need better token
```suggestion
  font-weight: $auro-text-body-default-weight;
```

2021-05-10 19:33 UTC, blackfalcon commented on src/_normalize.scss
> +  overflow: visible; /* 2 */
[This](https://github.com/AlaskaAirlines/AuroJavascriptDemo) is where this started. The order that normalizes has and our new enforcement of idiomatic ordering are in conflict. 

I don't really have an opinion on which way this goes, just dropping some history.

2021-05-10 19:33 UTC, blackfalcon commented on src/componentSupport/_table.scss
> +  border-collapse: collapse;
Yeah, I would expect something like

```scss
#{$scope}.auro_table
{
    display: block;
    overflow: scroll;

    width: auto;
    margin-bottom: $auro-size-xl;

    border-spacing: $auro-size-sm;
    border-collapse: collapse;
}
```

2021-05-10 19:33 UTC, blackfalcon commented on src/utilityClasses/_responsive.scss
> +    display: none $important;
I agree this reads weird, but I don't think it has an impact on render. For readability, in this case, I would think that it's ok to break the rules?

2021-05-10 19:33 UTC, blackfalcon commented on src/utilityMixins/_anchor-roleButton.scss
>      :host(:not(.is-touching)) & {
This util selector needs to be evaluated - see new issue  https://github.com/AlaskaAirlines/WebCoreStyleSheets/issues/78

This is NOT a priority but does need to be addressed someday.

2021-05-10 19:33 UTC, blackfalcon commented on src/utilityMixins/_anchor-roleButton.scss
> +    @error 'Invalid $env option. Please use `component` or `noncomponent`';
```suggestion
    @error 'Invalid `$env` option. Please use `component` or `noncomponent`';
```

2021-05-10 19:33 UTC, blackfalcon commented on src/utilityMixins/_anchor-roleTab.scss
> +    @error 'Invalid $env option. Please use `component` or `noncomponent`';
```suggestion
    @error 'Invalid `$env` option. Please use `component` or `noncomponent`';
```

2021-05-10 20:12 UTC, geoffrich commented on src/utilityClasses/_responsive.scss
> +    display: none $important;
I looked at the generated CSS and there doesn't seem to be a render impact, so the only question is readability.

2021-05-10 20:57 UTC, jason-capsule42 commented on src/utilityClasses/_responsive.scss
> +    display: none $important;
Since Media Queries do not alter the selector specificity the order would normally matter here so reverting it back would make sense. I think that putting @includes before rules is a good general rule of thumb but there will be exceptions - this is one of them.

I think Geoff is right and I would expect all 3 cases defined to end up with `display: none $important;`.

I'm going to revert this one back.

2021-05-10 21:23 UTC, jason-capsule42 commented on src/_normalize.scss
> +  -webkit-appearance: textfield; /* 1 */
Comment sequence order updated

2021-05-10 21:23 UTC, jason-capsule42 commented on src/_normalize.scss
> +  -webkit-appearance: button; /* 1 */
Comment sequence order updated

2021-05-10 21:44 UTC, blackfalcon commented on src/utilityMixins/_anchor-roleButton.scss
>      :host(:not(.is-touching)) & {
Correct. Issue #78 is NOT to be included in the scope of this update.

2021-05-11 03:32 UTC, blackfalcon approved these changes

2021-05-11 18:40 UTC, blackfalcon commented
Unable to merge, conflicts need to be resolved.

2021-05-12 17:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=73) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/WebCoreStyleSheets?pullRequest=73) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: blackfalcon<br/>:white_check_mark: jason-capsule42<br/>:x: semantic-release-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/WebCoreStyleSheets?pullRequest=73) it.</sub>

2021-05-13 20:04 UTC, blackfalcon approved these changes

2021-05-13 20:11 UTC, jason-capsule42 commented on src/_essentials.scss
> +#{$sym}#{$prefix}p {
This is what is current in the PR. What's not resolved here?

![Screen Shot 2021-05-13 at 1 10 59 PM](https://user-images.githubusercontent.com/23223137/118181479-aa8db700-b3ec-11eb-98ad-83f1035a260b.png)

2021-05-13 20:47 UTC, merged

2021-05-13 21:22 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 3.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/webcorestylesheets/v/3.3.1)
- [GitHub release](https://github.com/AlaskaAirlines/WebCoreStyleSheets/releases/tag/v3.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: